### PR TITLE
README

### PR DESCRIPTION
**Pull request by rohankishore**
I guess its all good now. Thank You!

### CODE REVIEW

**Comment by Lisra-git** [comment]
While this is definitely a good improvement, it delete most if not all the important part of the Readme

**Comment by rohankishore** [comment]
> While this is definitely a good improvement, it delete most if not all the important part of the Readme 

Oh sorry. I'll redo it. Thanks a lot 🙏🏻

**Comment by alaukikpachauri** [comment]
> > While this is definitely a good improvement, it delete most if not all the important part of the Readme
> 
> Oh sorry. I'll redo it. Thanks a lot 🙏🏻

**Comment by alaukikpachauri** [comment]
Hi, actually the app doesn't have the support for nothing's new product like cmf buds pro

**Comment by mrbrickstar** [comment]
See https://github.com/radiance-project/ear-pc/issues/17 and https://github.com/radiance-project/ear-pc/issues/22

**Pull request closed without merging**
